server:
  port: 8091
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  cloud:
    sentinel:
      transport:
      port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
      dashboard: localhost:8080 # 指定控制台服务的地址
      web-context-unify: false
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin
jpa:
  properties:
    hibernate:
      hbm2ddl:
        auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
feign:
  sentinel:
    enabled:true